# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20180430_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtags',
            name='tag_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение тега'),
        ),
    ]
