# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20180525_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='offer_article',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_characteristics',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_code',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_discount_term',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_id_on_site',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_image_url',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_minorder',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_minorder_value',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_photo_alt',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_pre_text',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_price_discount',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_price_from',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_price_to',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_priority',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_publish',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_urt_to_rubric',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_valuta',
        ),
    ]
