# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20180704_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
