# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-12 12:05
from __future__ import unicode_literals

from django.db import migrations


def migrate_prices(apps, schema_editor):

    Offer = apps.get_model('pages', 'Offers')
    Price = apps.get_model('pages', 'Price')
    PriceType = apps.get_model('pages', 'PriceType')

    price_type = PriceType.objects.order_by('id').first()
    if price_type is None:
        price_type = PriceType.objects.create(
            name='Цена'
        )

    for offer in Offer.objects.all():
        check_price = offer.prices.filter(price_type=price_type, value=offer.offer_price).first()
        if check_price is None:
            Price.objects.create(price_type=price_type, value=offer.offer_price, offer=offer)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20180704_2042'),
    ]

    operations = [
        migrations.RunPython(migrate_prices)
    ]
