# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20180712_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
