# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_pricetype_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AddField(
            model_name='category',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
