# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20180830_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_popylarity',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=2, verbose_name='Популярность товара'),
        ),
    ]
