# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-12 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_offers_offer_popylarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availability_code',
            field=models.IntegerField(default=0),
        ),
    ]
