# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_availability_availability_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=250)),
                ('tag_parent_tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Tags')),
            ],
            options={
                'verbose_name_plural': 'Кастомный поиск для группы товаров',
                'verbose_name': 'Кастомный поиск для группы товаров',
                'ordering': ['tag_parent_tag'],
            },
        ),
    ]
