# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_tags_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_search',
            name='offer_subtags',
            field=models.ManyToManyField(blank=True, to='pages.Subtags', verbose_name='Метки'),
        ),
    ]
