# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-18 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_tags_search_recursive_tag_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_search',
            name='order_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер старницы'),
        ),
        migrations.AlterField(
            model_name='tags_search',
            name='recursive_tag_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Tags_search', verbose_name='Следующий фильтр'),
        ),
    ]
