# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_auto_20181118_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_search',
            name='first_page_filtr',
            field=models.BooleanField(default=1, verbose_name='Первая страница фильтра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags_search',
            name='offer_subtags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='pages.Subtags', verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='tags_search',
            name='order_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер старницы фильтра'),
        ),
        migrations.AlterField(
            model_name='tags_search',
            name='recursive_tag_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='pages.Subtags', verbose_name='Родительский фильтр'),
        ),
    ]
